### ISSUE TITLE
Import LibCal events via CSV from lib-jobs, rather than ical

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/pul_library_drupal#1944]
Importing libcal events through the ical feed doesn't seem to work on PHP 8 (see https://github.com/pulibrary/princeton_ansible/issues/3350#issuecomment-1276740693) without serious changes to the date_ical module and/or the iCalcreator library (or possibly moving to a different module).

However, the friends_of_pul site imports libcal events through an RSS feed instead of ical.  Is this option possible for this site too?

- Ical URL used for the [library.princeton.edu importer](https://library.princeton.edu/import/libcal_events_workshops): https://libcal.princeton.edu/ical_subscribe.php?cid=12260&k=79a5e62a54
- RSS URL used for the [fpul.princeton.edu importer](https://fpul.princeton.edu/import/libcal_events): https://libcal.princeton.edu/rss.php?m=cat&iid=771&cid=12260&cat=50867

**Comment by kevinreiss** [comment]
We should be able to make this switch. We can test this in our next maint. Week.

**Comment by kevinreiss** [comment]
To test this the configuration of the feeds importer for events will need to be re-configured to pull field values from the RSS rather than ICS feed. Steps to take in your local environment to test this. 

1. Structure -> Feeds Importers -> LibCal Events - Workshops -> Override
2. First Check The "Mappings" settings under "Processor" and note the fields the feed is looking for. Confirm versions of these exist in the RSS feed.
3. If the mapping is straightforward update the Parser to parse RSS
4. Return to the Processor and re-map the fields. 
5. Go to /import/libcal_events_workshops and update the URL to use the RSS feed. 
6. Test the feed interactively from this page. 
7.

**Comment by christinach** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/pul_library_drupal/1944?planning-poker) with Zenhub @sandbergja @kayiwa @maxkadel @rladdusaw

**Comment by kevinreiss** [comment]
Jane and I will give this a test.

**Comment by kevinreiss** [comment]
Closed by https://github.com/pulibrary/pul_library_drupal/pull/1949
