### ISSUE TITLE
Best Bet's WorldCat result shows HTML 'a' tag for link instead of creating the link

### ISSUE THREAD

**Issue by lizgarciao** [pulibrary/pul_library_drupal#2021]
### Expected behavior
The last sentence in the WorldCat result should contain a link that says "Interlibrary Loan" and be clickable.

### Actual behavior
* I can see the HTML 'a' tag to create the link, instead of the clickable link.
* Seen on Google Chrome.

### Steps to replicate
See: [error in website](https://library.princeton.edu/find/all/cat)

### Impact of this bug
Link is not displaying correctly and users cannot click on it.

**Comment by kevinreiss** [comment]
The issue comes from the import configuration we have for library databases from libguides. Descriptions should be imported as html rather than plain text. The linked PR updates the configuration for the importer. In this instance the "Best Bet" content type referenced the Worldcat Database content type which is where the description rendered is pulled from.

**Comment by sandbergja** [comment]
Closed by #2022
